services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - app_network

  frontend:
    build:
      context: . 
      dockerfile: ./web/Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge